namespace BoldDesk.Cli;

public static class CompletionHelper
{
    public static string GenerateBashCompletion()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Bash completion for bolddesk");
        sb.AppendLine("_bolddesk() {");
        sb.AppendLine("  local cur prev words cword");
        sb.AppendLine("  _get_comp_words_by_ref -n : cur prev words cword 2>/dev/null || {");
        sb.AppendLine("    cur=${COMP_WORDS[COMP_CWORD]}");
        sb.AppendLine("    prev=${COMP_WORDS[COMP_CWORD-1]}");
        sb.AppendLine("    words=(${COMP_WORDS[@]})");
        sb.AppendLine("    cword=$COMP_CWORD");
        sb.AppendLine("  }");
        sb.AppendLine();
        sb.AppendLine("  COMPREPLY=()");
        sb.AppendLine();
        sb.AppendLine("  if [[ $cword -eq 1 ]]; then");
        sb.AppendLine("    COMPREPLY=( $(compgen -W \"config tickets brands agents worklogs contact-groups contacts install-completion\" -- \"$cur\") )");
        sb.AppendLine("    return 0");
        sb.AppendLine("  fi");
        sb.AppendLine();
        sb.AppendLine("  case \"${words[1]}\" in");
        sb.AppendLine("    tickets|brands|agents|worklogs)");
        sb.AppendLine("      if [[ $cword -eq 2 ]]; then");
        sb.AppendLine("        COMPREPLY=( $(compgen -W \"list\" -- \"$cur\") )");
        sb.AppendLine("      fi");
        sb.AppendLine("      ;;");
        sb.AppendLine("    contact-groups)");
        sb.AppendLine("      if [[ $cword -eq 2 ]]; then");
        sb.AppendLine("        COMPREPLY=( $(compgen -W \"list get count contacts notes export\" -- \"$cur\") )");
        sb.AppendLine("        return 0");
        sb.AppendLine("      fi");
        sb.AppendLine("      case \"${words[2]}\" in");
        sb.AppendLine("        get)");
        sb.AppendLine("          if [[ $prev == \"--name\" ]]; then");
        sb.AppendLine("            local names=$(bolddesk complete contact-groups names --prefix \"$cur\" --limit 200 2>/dev/null)");
        sb.AppendLine("            COMPREPLY=( $(compgen -W \"$names\" -- \"$cur\") )");
        sb.AppendLine("            return 0");
        sb.AppendLine("          fi");
        sb.AppendLine("          if [[ $prev == \"--id\" ]]; then");
        sb.AppendLine("            local ids=$(bolddesk complete contact-groups ids --prefix \"$cur\" --limit 200 2>/dev/null)");
        sb.AppendLine("            COMPREPLY=( $(compgen -W \"$ids\" -- \"$cur\") )");
        sb.AppendLine("            return 0");
        sb.AppendLine("          fi");
        sb.AppendLine("          ;;");
        sb.AppendLine("        contacts)");
        sb.AppendLine("          if [[ $cword -eq 4 && ${words[3]} == \"list\" ]]; then");
        sb.AppendLine("            local ids=$(bolddesk complete contact-groups ids --prefix \"$cur\" --limit 200 2>/dev/null)");
        sb.AppendLine("            COMPREPLY=( $(compgen -W \"$ids\" -- \"$cur\") )");
        sb.AppendLine("            return 0");
        sb.AppendLine("          fi");
        sb.AppendLine("          if [[ $cword -eq 4 && ( ${words[3]} == \"add\" || ${words[3]} == \"remove\" ) ]]; then");
        sb.AppendLine("            local ids=$(bolddesk complete contact-groups ids --prefix \"$cur\" --limit 200 2>/dev/null)");
        sb.AppendLine("            COMPREPLY=( $(compgen -W \"$ids\" -- \"$cur\") )");
        sb.AppendLine("            return 0");
        sb.AppendLine("          fi");
        sb.AppendLine("          ;;");
        sb.AppendLine("        export)");
        sb.AppendLine("          if [[ $cword -eq 3 ]]; then");
        sb.AppendLine("            COMPREPLY=( $(compgen -W \"groups contacts\" -- \"$cur\") )");
        sb.AppendLine("            return 0");
        sb.AppendLine("          fi");
        sb.AppendLine("          if [[ $cword -eq 4 && ${words[3]} == \"contacts\" ]]; then");
        sb.AppendLine("            local ids=$(bolddesk complete contact-groups ids --prefix \"$cur\" --limit 200 2>/dev/null)");
        sb.AppendLine("            COMPREPLY=( $(compgen -W \"$ids\" -- \"$cur\") )");
        sb.AppendLine("            return 0");
        sb.AppendLine("          fi");
        sb.AppendLine("          ;;");
        sb.AppendLine("      esac");
        sb.AppendLine("      ;;");
        sb.AppendLine("  esac");
        sb.AppendLine("}");
        sb.AppendLine("complete -o bashdefault -o default -F _bolddesk bolddesk 2>/dev/null || complete -F _bolddesk bolddesk");
        return sb.ToString();
    }

    public static string GenerateZshCompletion()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("#compdef bolddesk");
        sb.AppendLine("_bolddesk() {");
        sb.AppendLine("  local -a commands");
        sb.AppendLine("  commands=(config tickets brands agents worklogs 'contact-groups' contacts 'install-completion')");
        sb.AppendLine("  if (( CURRENT == 2 )); then");
        sb.AppendLine("    _describe -t commands 'commands' commands");
        sb.AppendLine("    return");
        sb.AppendLine("  fi");
        sb.AppendLine("  case $words[2] in");
        sb.AppendLine("    tickets|brands|agents|worklogs)");
        sb.AppendLine("      compadd list ;;");
        sb.AppendLine("    contact-groups)");
        sb.AppendLine("      if (( CURRENT == 3 )); then");
        sb.AppendLine("        compadd list get count contacts notes export");
        sb.AppendLine("        return");
        sb.AppendLine("      fi");
        sb.AppendLine("      case $words[3] in");
        sb.AppendLine("        get)");
        sb.AppendLine("          if [[ $words[CURRENT-1] == --name ]]; then");
        sb.AppendLine("            compadd $(bolddesk complete contact-groups names --prefix \"$words[CURRENT]\" --limit 200 2>/dev/null)");
        sb.AppendLine("            return");
        sb.AppendLine("          fi");
        sb.AppendLine("          if [[ $words[CURRENT-1] == --id ]]; then");
        sb.AppendLine("            compadd $(bolddesk complete contact-groups ids --prefix \"$words[CURRENT]\" --limit 200 2>/dev/null)");
        sb.AppendLine("            return");
        sb.AppendLine("          fi");
        sb.AppendLine("          ;;");
        sb.AppendLine("        contacts)");
        sb.AppendLine("          if (( CURRENT == 5 )) && [[ $words[4] == list || $words[4] == add || $words[4] == remove ]]; then");
        sb.AppendLine("            compadd $(bolddesk complete contact-groups ids --prefix \"$words[CURRENT]\" --limit 200 2>/dev/null)");
        sb.AppendLine("            return");
        sb.AppendLine("          fi");
        sb.AppendLine("          ;;");
        sb.AppendLine("        export)");
        sb.AppendLine("          if (( CURRENT == 4 )); then compadd groups contacts; return; fi");
        sb.AppendLine("          if (( CURRENT == 5 )) && [[ $words[4] == contacts ]]; then");
        sb.AppendLine("            compadd $(bolddesk complete contact-groups ids --prefix \"$words[CURRENT]\" --limit 200 2>/dev/null)");
        sb.AppendLine("            return");
        sb.AppendLine("          fi");
        sb.AppendLine("          ;;");
        sb.AppendLine("      esac");
        sb.AppendLine("      ;;");
        sb.AppendLine("  esac");
        sb.AppendLine("}");
        sb.AppendLine("_bolddesk");
        return sb.ToString();
    }
}
